#############################################################################
# Generated by PAGE version 4.12
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Levenim MT} -size 13 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Levenim MT} -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {Levenim MT} -size 9 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra42
    set site_3_0 $base.fra43
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 745x578+242+64
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 750
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Emotion Detection"
    vTcl:DefineAlias "$top" "Toplevel2" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra42 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 165 \
        -width 715 
    vTcl:DefineAlias "$top.fra42" "Frame1" vTcl:WidgetProc "Toplevel2" 1
    set site_3_0 $top.fra42
    button $site_3_0.but48 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Tweet Text} 
    vTcl:DefineAlias "$site_3_0.but48" "traintextbutton" vTcl:WidgetProc "Toplevel2" 1
    button $site_3_0.but49 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Tweet Values} 
    vTcl:DefineAlias "$site_3_0.but49" "trainvaluesbutton" vTcl:WidgetProc "Toplevel2" 1
    text $site_3_0.tex54 \
        -background white -font TkTextFont -foreground black -height 24 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 354 -wrap word 
    .top37.fra42.tex54 configure -font TkTextFont
    .top37.fra42.tex54 insert end text
    vTcl:DefineAlias "$site_3_0.tex54" "trainingtextbox" vTcl:WidgetProc "Toplevel2" 1
    text $site_3_0.tex55 \
        -background white -font TkTextFont -foreground black -height 24 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 354 -wrap word 
    .top37.fra42.tex55 configure -font TkTextFont
    .top37.fra42.tex55 insert end text
    vTcl:DefineAlias "$site_3_0.tex55" "trainingvaluesbox" vTcl:WidgetProc "Toplevel2" 1
    button $site_3_0.but56 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Train 
    vTcl:DefineAlias "$site_3_0.but56" "starttrainingbutton" vTcl:WidgetProc "Toplevel2" 1
    checkbutton $site_3_0.che58 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Reset -variable che58 
    vTcl:DefineAlias "$site_3_0.che58" "resettraincheckbox" vTcl:WidgetProc "Toplevel2" 1
    label $site_3_0.lab59 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -text Training 
    vTcl:DefineAlias "$site_3_0.lab59" "Label1" vTcl:WidgetProc "Toplevel2" 1
    place $site_3_0.but48 \
        -in $site_3_0 -x 100 -y 50 -width 93 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 105 -y 90 -width 88 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex54 \
        -in $site_3_0 -x 230 -y 50 -width 354 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex55 \
        -in $site_3_0 -x 230 -y 90 -width 354 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 550 -y 130 -width 67 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che58 \
        -in $site_3_0 -x 470 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 20 -y 20 -anchor nw -bordermode ignore 
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 175 \
        -width 715 
    vTcl:DefineAlias "$top.fra43" "Frame2" vTcl:WidgetProc "Toplevel2" 1
    set site_3_0 $top.fra43
    button $site_3_0.but50 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Tweet  Text} 
    vTcl:DefineAlias "$site_3_0.but50" "testtextbutton" vTcl:WidgetProc "Toplevel2" 1
    button $site_3_0.but51 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Tweet Values} 
    vTcl:DefineAlias "$site_3_0.but51" "testvaluesbutton" vTcl:WidgetProc "Toplevel2" 1
    text $site_3_0.tex52 \
        -background white -font TkTextFont -foreground black -height 24 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 344 -wrap word 
    .top37.fra43.tex52 configure -font TkTextFont
    .top37.fra43.tex52 insert end text
    vTcl:DefineAlias "$site_3_0.tex52" "testingtextbox" vTcl:WidgetProc "Toplevel2" 1
    text $site_3_0.tex53 \
        -background white -font TkTextFont -foreground black -height 24 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 344 -wrap word 
    .top37.fra43.tex53 configure -font TkTextFont
    .top37.fra43.tex53 insert end text
    vTcl:DefineAlias "$site_3_0.tex53" "testingvaluesbox" vTcl:WidgetProc "Toplevel2" 1
    button $site_3_0.but57 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Test 
    vTcl:DefineAlias "$site_3_0.but57" "starttestingbutton" vTcl:WidgetProc "Toplevel2" 1
    label $site_3_0.lab60 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -text Testing 
    vTcl:DefineAlias "$site_3_0.lab60" "Label2" vTcl:WidgetProc "Toplevel2" 1
    place $site_3_0.but50 \
        -in $site_3_0 -x 110 -y 60 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 110 -y 100 -anchor nw -bordermode ignore 
    place $site_3_0.tex52 \
        -in $site_3_0 -x 240 -y 60 -width 344 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex53 \
        -in $site_3_0 -x 240 -y 100 -width 344 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but57 \
        -in $site_3_0 -x 580 -y 140 -width 73 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 20 -y 10 -anchor nw -bordermode ignore 
    button $top.but44 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Evaluate Text} 
    vTcl:DefineAlias "$top.but44" "evaluatetextbutton" vTcl:WidgetProc "Toplevel2" 1
    button $top.but45 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {GUI Evaluation} 
    vTcl:DefineAlias "$top.but45" "guievaluationbutton" vTcl:WidgetProc "Toplevel2" 1
    button $top.but46 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Information 
    vTcl:DefineAlias "$top.but46" "informationbutton" vTcl:WidgetProc "Toplevel2" 1
    button $top.but47 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Exit 
    vTcl:DefineAlias "$top.but47" "exitbutton" vTcl:WidgetProc "Toplevel2" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra42 \
        -in $top -x 20 -y 10 -width 715 -relwidth 0 -height 165 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra43 \
        -in $top -x 20 -y 200 -width 715 -relwidth 0 -height 175 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but44 \
        -in $top -x 30 -y 400 -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 320 -y 400 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 610 -y 400 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 320 -y 500 -width 130 -relwidth 0 -height 35 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

